apiVersion: v1
kind: Pod
metadata:
  name: app-with-init
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-container-1
    image: busybox
    command: ['sh', '-c', 'echo Starting first init container; sleep 4;echo First init container completed;']
  - name: init-container-2
    image: busybox
    command: ['sh', '-c', 'echo Starting 2nd init container; sleep 4;echo second init container completed;']                                                                                                           
