apiVersion: v1
kind: Pod
metadata:
  name: emptydir-test-pod
spec:
  containers:
  - image: busybox
    name: producer
    command: ['sh', '-c', 'echo Producer is generating data > /data/data.txt ; sleep 3600']

    volumeMounts:
    - mountPath: /data
      name: cache-volume

  - image: busybox
    name: consumer
    command: ['sh', '-c', 'sleep 60; cat /data/data.txt ; sleep 3600']

    volumeMounts:
    - mountPath: /data
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
