apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: httpd
spec:
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
