apiVersion: v1
kind: Pod
metadata:
 name: node-affinity-pod
spec:
 affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: disktype
           operator: In
           values:
           - ssd
     preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 1
       preference:
         matchExpressions:
         - key: node-owner
           operator: In
           values:
           - qa
           - test
 containers:
 - name: web-server
   image: nginx
