apiVersion: v1
kind: Pod
metadata:
 name: pod-affinity-pod
spec:
 affinity:
   podAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
     - labelSelector:
         matchExpressions:
         - key: team
           operator: In
           values:
           - qa
       topologyKey: kubernetes.io/hostname
   podAntiAffinity:
     preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 100
       podAffinityTerm:
         labelSelector:
           matchExpressions:
           - key: team
             operator: In
             values:
             - dev
         topologyKey: kubernetes.io/hostname
 containers:
 - name: pod-affinity-container
   image: nginx

